### ISSUE TITLE
API error when running

### ISSUE THREAD

**Issue by jedd** [whitfin/limber#2]
Hi,

Installed on Debian 10 (buster) using 'apt install cargo' then 'cargo install limber'

limber --version ==> 1.0.1

Running against remote or local host, with or without an index name, results in the same error.

I've tried remotes with 7.1.0 and 6.7.1 , and my localhost is running 7.1.1

Simplest example:

> limber export http://localhost:9200 
> Error: ErrorMessage { msg: "API error returned from Elasticsearch. Caused by: illegal argument: \'query malformed, empty clause found at [1:11]\'" }

**Comment by romulus-ai** [comment]
Same here:

> limber --version
limber 1.0.2

> curl localhost:9201
{
  "name" : "es/0",
  "cluster_name" : "msd24d18b",
  "cluster_uuid" : "98Hx0bLgSMapQIGXeqYExw",
  "version" : {
    "number" : "6.7.2",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "56c6e48",
    "build_date" : "2019-04-29T09:05:50.290371Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

thats sad, seems to be a powerful tool..

**Comment by whitfin** [comment]
Finally got back around to cleaning up this project :) should be all resolved with the latest dependency bumps and migration to the official library.
